<?php

namespace App\Enums\Invoice;

enum DocumentType: string
{
    case EARCHIVE = 'EARCHIVE';
    case EINVOICE = 'EINVOICE';
    case INCOMING_EINVOICE = 'INCOMING_EINVOICE';
    case SENT_REPLY = 'SENT_REPLY';
    case RECEIVED_REPLY = 'RECEIVED_REPLY';
    case DESPATCHADVICE = 'DESPATCHADVICE';
    case INCOMING_DESPATCH = 'INCOMING_DESPATCH';
    case INCOMING_RECEIPTADVICE = 'INCOMING_RECEIPTADVICE';
    case RECEIPTADVICE = 'RECEIPTADVICE';
}
