<?php

namespace App\Services\Integrations\InvoiceProviders\TrendyolEFatura\Enums;

enum MarketplaceExpenseType: string
{
    case HKSKOMISYON = 'HKSKOMISYON';
    case HKSKOMISYONKDV = 'HKSKOMISYONKDV';
    case HKSNAVLUN = 'HKSNAVLUN';
    case HKSNAVLUNKDV = 'HKSNAVLUNKDV';
    case HKSHAMMALIYE = 'HKSHAMMALIYE';
    case HKSHAMMALIYEKDV = 'HKSHAMMALIYEKDV';
    case HKSNAKLIYE = 'HKSNAKLIYE';
    case HKSNAKLIYEKDV = 'HKSNAKLIYEKDV';
    case HKSGVTEVKIFAT = 'HKSGVTEVKIFAT';
    case HKSBAGKURTEVKIFAT = 'HKSBAGKURTEVKIFAT';
    case HKSRUSUM = 'HKSRUSUM';
    case HKSRUSUMKDV = 'HKSRUSUMKDV';
    case HKSTICBORSASI = 'HKSTICBORSASI';
    case HKSTICBORSASIKDV = 'HKSTICBORSASIKDV';
    case HKSMILLISAVUNMAFON = 'HKSMILLISAVUNMAFON';
    case HKSMSFONKDV = 'HKSMSFONKDV';
    case HKSDIGERMASRAFLAR = 'HKSDIGERMASRAFLAR';
    case HKSDIGERKDV = 'HKSDIGERKDV';
}
